# Site settings
title: univ2dev(&me) 
author:
    name: David Karwowski
    url: www.dkarwowski.com
    email: info@dkarwowski.com
    github: dkarwowski
    linkedin: dkarwowski
    address:
        street: 69 Capitol Drive
        town: Shelton, CT 06484
        country: United States

description: > # this means to ignore newlines until "baseurl:"
    looking for the challenges to learn something
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dkarwowski.com" # the base hostname & protocol for your site
github_username:  dkarwowski

# Build settings
markdown: kramdown
highlighter: rouge

# permalink
permalink: pretty

paginate: 10

gems: [jekyll-paginate]
