# Site settings
title: David Karwowski
email: david@dkarwowski.me
description: > # this means to ignore newlines until "baseurl:"
    A student at the University of Connecticut trying to understand stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dkarwowski.me" # the base hostname & protocol for your site
github_username:  dkarwowski

# Build settings
markdown: kramdown
highlighter: pygments

# permalink
permalink: pretty
